### ISSUE TITLE
Hardcoded accesstoken in app.js

### ISSUE THREAD

**Issue by iH8** [bmcbride/geojson-share-maps#1]
Unless you're rich enough to pay for someone else's mapbox views, i'de remove that if i was you and make it configurable.

**Comment by bmcbride** [comment]
We'll see how it goes... I'd really like to keep it available without forcing an access token. Ideally folks will fork the repo and swap in their own maps, but if it becomes an issue or exceeds my quota, I'll either force users to provide a token or see if the nice folks at Mapbox might be willing to work with us :)
