### ISSUE TITLE
Difficulties with implementation

### ISSUE THREAD

**Issue by kappa44** [bmcbride/geojson-share-maps#2]
[Hello,](url)

This is a great app. Thanks for the work. Unfortunately I'm having problems implementing it on my own git page. I uploaded the files and created the page etc. but the data isn't loading. See here: [maptest](http://kappa44.github.io/maptest/)

The files I'm using on my git page were totally unedited from what was in your repository. I just wanted to test it out before I started making changes. Am I missing a step? Do I have to add my own mapbox AccessToken code in app.js? I want to do a demo app similar to the NYC Coffee Shop map you have listed in the demos. I have a mapbox account but have yet to create a map there.

Any assistance you can give on why the data in my demo git page isn't loading would be greatly appreciated. I am a bit of a git novice.

Thanks again for providing such a great demo app.

**Comment by kappa44** [comment]
I've been looking at the code and reading the mapbox api documentation. I've also been looking at the app.js file. I think I can clarify my question. I can't figure out how the geojson data is being loaded into the app. Is it already in the map that is being pulled from mapbox (as in the NYC Coffee map) or is it in a geojson file that is uploaded to the app directories (similar to the technique described here: [Mapbox Documentation](https://www.mapbox.com/mapbox.js/example/v1.0.0/geojson-marker-from-url/).

Apologies but I can't figure out from looking through app.js how the data is being loaded and, therefore,  how the mapbox api url is being generated. Any clarification you can give on that score would be greatly appreciated. Thanks again.

**Comment by bmcbride** [comment]
You shouldn't have to change any code to get it to work (though please use your own Mapbox token [here](https://github.com/bmcbride/geojson-share-maps/blob/master/assets/js/app.js#L1)). Everything (including the GeoJSON file) should be configured via [URL parameters](https://github.com/bmcbride/geojson-share-maps#url-parameters). The [Coffee Shop](http://bmcbride.github.io/geojson-share-maps/?src=http://api.tiles.mapbox.com/v3/mapbox.o11ipb8h/markers.geojson&fields=name,description&title=NYC%20Coffee%20Shops&title_field=name&attribution=Courtesy%20of%20Mapbox&cluster=false) demo pulls GeoJSON from a Mapbox account, while the [DC WiFi Social](http://bmcbride.github.io/geojson-share-maps/?src=https://raw.githubusercontent.com/benbalter/dc-wifi-social/master/bars.geojson&fields=name,address&title=DC%20WiFi%20Social&title_field=name&attribution=https://github.com/benbalter/dc-wifi-social) example pulls from a GeoJSON file hosted on GitHub. Take a look at the `src` parameter in the URLs to see how it is configured.
