### ISSUE TITLE
TypeError: urlParams.src is undefined

### ISSUE THREAD

**Issue by achmadmaskuri** [bmcbride/geojson-share-maps#3]
I've installed GeoJSON-share-maps in wamp server system windows. I get an error TypeError: urlParams.src is undefined line 145 in app.js. Applications are only visible loading animation. Thank you

C:\wamp\www\geojson-share-maps\assets\js\app.js:
  144    featureLayer.clearLayers();
  145    $("#feature-list tbody").empty();
  146:   if (urlParams.src.indexOf(".topojson") > -1) {
  147      omnivore.topojson(urlParams.src, null, featureLayer).on("ready", function(layer) {
  148        $("#loading").hide();

**Comment by bmcbride** [comment]
You need to provide the GeoJSON source in the `src` URL parameter. See https://github.com/bmcbride/geojson-share-maps#url-parameters.
