### ISSUE TITLE
non mapbox dependent version

### ISSUE THREAD

**Issue by vlasvlasvlas** [bmcbride/geojson-share-maps#4]
Hi i was wondering if one can rebuild these to make a non mapbox dependent versión , since they could charge you for using their service.

What would be the correct changes to replace the mapbox api with  Leaflet api only?
Thanks!

**Comment by bmcbride** [comment]
The main reason for using Mapbox.js is that is supports styling from GeoJSON properties via https://www.mapbox.com/help/define-simplestyle/.

**Comment by vlasvlasvlas** [comment]
And is there a simple way to avoid using mapbox api?

i mean i see the other main thing i need to replace is L.mapbox.featureLayer() , whats the correct way of replacing L.mapbox.featureLayer();  with leaflet feature layer? thanks!
