### ISSUE TITLE
limited listing at sidebar, but full list at geojson

### ISSUE THREAD

**Issue by vlasvlasvlas** [bmcbride/geojson-share-maps#5]
Hi, i'm having a strange issue,

i'm seeing full listing at geojson (4example 100 markers) but on sidebar i'm seeing less items (4example 70 markers at sidebar)

why this may be happening? there are aprox 600 markers at geojson but sidebar order a-z just shows from A to letter L.

txs!

**Comment by vlasvlasvlas** [comment]
ok, same happens here:
http://bmcbride.github.io/geojson-share-maps/?src=https://web.fulcrumapp.com/shares/82982e4c55707a34.geojson&fields=name,full_name,ground,league,city,state_province,country,photo&title=Football%20Clubs%20of%20Europe&title_field=name&attribution=Courtesy%20of%20Coleman%20McCormick&cluster=true

sidebar only shows from A  letter L 

but geojson is much more extense.

for ex i can search Sivasspor and get filtered, but its not on the sidebar list wihtout filtering.

**Comment by vlasvlasvlas** [comment]
ok, my mistake.

https://github.com/javve/list.js/issues/236

must set listjs page limit.

**Comment by bmcbride** [comment]
Glad you got it figured out!
