### ISSUE TITLE
Ability to call an api url that has its own parameters, i.e. ? and &

### ISSUE THREAD

**Issue by sasignell** [bmcbride/geojson-share-maps#6]
e.g. https://adirondackatlas.org/api/v1/search.php?query=eggs&geojson=true

**Comment by bmcbride** [comment]
@sasignell Try this: http://bmcbride.github.io/geojson-share-maps/?src=https://adirondackatlas.org/api/v1/search.php?query%3Deggs%26geojson%3Dtrue&fields=name,keywords&title_field=ADK Atlas

**Comment by bmcbride** [comment]
@sasignell Also, if you prefer Google Maps, you can use this: https://bmcbride.github.io/mapps/?src=https://adirondackatlas.org/api/v1/search.php?query%3Deggs%26geojson%3Dtrue&fields=name,keywords&title=ADK%20Atlas&sortfield=name
